name: CI
on: [pull_request]
permissions:
  contents: read
jobs:
  lint-code:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Prepare GO env
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0

  build-code:
    name: sample-build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare GO env
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build ci/sample.go
        run: go build ci/sample.go
