name: CI
on: [pull_request]
permissions:
  contents: read
env:
  go_version: '1.21'
jobs:
  lint-code:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Prepare GO env
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}
          cache: false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2

  build-code:
    name: sample-build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare GO env
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}
          cache: false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build ci/sample.go
        run: go build ci/sample.go

  format-code:
    name: gofmt
    runs-on: ubuntu-latest
    steps:
      - name: Prepare GO env
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}
          cache: false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run gofmt
        run: "gofmt -d -e . | tee test_results.log"
      - name: Verify output
        run: "! grep -E + test_results.log -q"
